Completed prep-javascript-conditionals
joshuaLeeT/prep-1122-code-solutions pull request #15
Opened 2022-11-25 18:55 UTC by joshuaLeeT

![image](https://user-images.githubusercontent.com/31152745/204042045-2fb56f65-ac13-4313-8078-bd988e33cf5c.png)

2022-11-25 21:48 UTC, thebearingedge requested changes

2022-11-25 21:48 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +    } else {
We'll want to change this from "and" `&&` to "or" `||` since the `dayOfTheWeek` can't be both `'saturday'` and `'sunday'` at the same time

2022-11-26 00:05 UTC, joshuaLeeT commented
![image](https://user-images.githubusercontent.com/31152745/204064343-f44d452c-068f-42db-add0-ea246e1c985e.png)
![image](https://user-images.githubusercontent.com/31152745/204064365-9d4c2ec2-eebf-4433-bab9-6e9131ab366a.png)

2022-11-26 15:36 UTC, thebearingedge approved these changes

2022-11-26 16:50 UTC, merged